# Plugin version
version = 10.0.0

# Airship Framework proxy version
airshipFrameworkProxyVersion = 15.8.0

# Kotlin version required to read the bundled Airship SDK metadata
kotlinVersion = 2.2.20

# Android compile SDK version
androidCompileSdkVersion = 36

# Android target SDK version
androidTargetSdkVersion = 36

# Android min SDK version
androidMinSdkVersion = 23

# Google Play Services Resolver tag
playServicesResolver = v1.2.187

unityVersion = 6000.2.8f1
