
plugins {
    id 'com.android.library'
    id 'maven-publish'
    id 'org.jetbrains.kotlin.android'
}

group = 'com.urbanairship.unitysupport'
version = airshipProperties.version
description = "Urban Airship Android Unity Plugin"


android {
    lintOptions {
        abortOnError false
    }

    namespace 'com.urbanairship.unityplugin'

    compileSdk airshipProperties.androidCompileSdkVersion.toInteger()

    defaultConfig {
        minSdk airshipProperties.androidMinSdkVersion.toInteger()
        targetSdk airshipProperties.androidTargetSdkVersion.toInteger()

        buildConfigField "String", "PLUGIN_VERSION", "\"${airshipProperties.version}\""
    }

    buildFeatures {
        buildConfig = true
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }

//   kotlinOptions {
//       jvmTarget = '1.8'
//   }
}


dependencies {
    implementation 'androidx.core:core-ktx:1.15.0'
    def lifecycle = '2.7.0'
//    implementation 'androidx.core:core-ktx:1.15.0'
    compileOnly files('libs/unity-classes.jar')
    implementation "androidx.annotation:annotation:$airshipProperties.androidxAnnotationVersion"
//    implementation "androidx.lifecycle:lifecycle-common-java8:$lifecycle"
//    implementation "androidx.lifecycle:lifecycle-process:$lifecycle"
//    implementation "androidx.lifecycle:lifecycle-livedata-ktx:$lifecycle"
//    implementation "androidx.lifecycle:lifecycle-runtime-ktx:$lifecycle"
//    implementation "androidx.lifecycle:lifecycle-runtime-compose:$lifecycle"
//    implementation "androidx.lifecycle:lifecycle-viewmodel:$lifecycle"
//    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle"
    // implementation("androidx.lifecycle:lifecycle-common-java8") {
    //     version {
    //         strictly("$lifecycle")
    //     }
    // }
    // implementation("androidx.lifecycle:lifecycle-process") {
    //     version {
    //         strictly("$lifecycle")
    //     }
    // }
    // implementation("androidx.lifecycle:lifecycle-livedata-ktx") {
    //     version {
    //         strictly("$lifecycle")
    //     }
    // }
    // implementation("androidx.lifecycle:lifecycle-runtime-ktx") {
    //     version {
    //         strictly("$lifecycle")
    //     }
    // }
    // implementation("androidx.lifecycle:lifecycle-runtime-compose") {
    //     version {
    //         strictly("$lifecycle")
    //     }
    // }
    // implementation("androidx.lifecycle:lifecycle-viewmodel") {
    //     version {
    //         strictly("$lifecycle")
    //     }
    // }
    // implementation("androidx.lifecycle:lifecycle-viewmodel-ktx") {
    //     version {
    //         strictly("$lifecycle")
    //     }
    // }
    // implementation 'androidx.startup:startup-runtime:1.2.0'

    // implementation "com.urbanairship.android:urbanairship-fcm:${airshipProperties.androidAirshipVersion}"
    // implementation "com.urbanairship.android:urbanairship-message-center:${airshipProperties.androidAirshipVersion}"
    // implementation "com.urbanairship.android:urbanairship-automation:${airshipProperties.androidAirshipVersion}"
    // implementation "com.urbanairship.android:urbanairship-preference-center:${airshipProperties.androidAirshipVersion}"
    implementation "com.urbanairship.android:airship-framework-proxy:${airshipProperties.airshipFrameworkProxyVersion}"
    // implementation("com.urbanairship.android:airship-framework-proxy:${airshipProperties.airshipFrameworkProxyVersion}") {
    //     exclude group: 'androidx.lifecycle', module: 'lifecycle-common-java8'
    //     exclude group: 'androidx.lifecycle', module: 'lifecycle-process'
    //     exclude group: 'androidx.lifecycle', module: 'lifecycle-livedata-ktx'
    //     exclude group: 'androidx.lifecycle', module: 'lifecycle-runtime-ktx'
    //     exclude group: 'androidx.lifecycle', module: 'lifecycle-runtime-compose'
    //     exclude group: 'androidx.lifecycle', module: 'lifecycle-viewmodel'
    //     exclude group: 'androidx.lifecycle', module: 'lifecycle-viewmodel-ktx'
    // }
}

task copyUnityClassesJar(type: Copy) {
  from file(getUnityClassesPath()).getParent()
  include file(getUnityClassesPath()).getName()
  rename ("classes.jar", "unity-classes.jar")
  into 'libs'
}

preBuild.dependsOn copyUnityClassesJar
publish.dependsOn assemble

def getUnityClassesPath() {
    def path = System.getProperty("UNITY_CLASSES_JAR")
    if (path == null || path.isEmpty()) {
        path = System.getenv("UNITY_CLASSES_JAR")
    }

    if (path == null || path.isEmpty() || !file(path).exists()) {
        path = "/Applications/Unity/Hub/Editor/$airshipProperties.unityVersion/PlaybackEngines/AndroidPlayer/Variations/mono/Release/Classes/classes.jar"
    }

    return path
}