name: CI

on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build Docs
        run: |
          sudo apt-get install doxygen
          ./gradlew docs:build
        
      # Build
      - name: Build Android
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.ULRICH_UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.ULRICH_UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.ULRICH_UNITY_SERIAL }}
        with:
          targetPlatform: Android

      - name: Build iOS
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.ULRICH_UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.ULRICH_UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.ULRICH_UNITY_SERIAL }}
        with:
          allowDirtyBuild: true
          targetPlatform: iOS

      - name: check directory
        if: always()
        run: |
          ls -R /opt/Unity/

      - name: generate unity package
        if: always()
        run: |
          ./gradlew build
          ls build/
             
