name: CI

on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - iOS # Build an iOS player.
          - Android # Build an Android .apk standalone app.

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build Docs
        run: |
          sudo apt-get install doxygen
          ./gradlew docs:build
        
      # Build
      - name: Build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.ULRICH_UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.ULRICH_UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.ULRICH_UNITY_SERIAL }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}

      - uses: game-ci/unity-test-runner@v4
        env:
          UNITY_EMAIL: ${{ secrets.ULRICH_UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.ULRICH_UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.ULRICH_UNITY_SERIAL }}
        with:
          unityVersion: 2022.3.15f1
          packageMode: true
          projectPath: build/
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: Build
      #     path: build

      - name: check directory
        if: always()
        run: |
          pwd
          ls build/
          

      # - name: generate unity package
      #   if: always()
      #   run: |
      #     ./gradlew build
      #     ls build/
             
