name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

jobs:
  plugin:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - iOS # Build an iOS player.
          - Android # Build an Android .apk standalone app.
          
    steps:
      - uses: actions/checkout@v4

      - name: Get the version
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Verify Version
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          PLUGIN_VERSION=$(./gradlew -q getPluginVersion)
          if [[ $PLUGIN_VERSION = $VERSION ]]; then exit 0 ; else exit 1; fi

      - name: Get the release notes
        id: get_release_notes
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          delimiter="$(openssl rand -hex 8)"
          {
            echo "NOTES<<${delimiter}"
            awk "/## Version $VERSION/{flag=1;next}/## Version/{flag=0}flag" CHANGELOG.md
            echo ${delimiter}
          } >> $GITHUB_OUTPUT

      - name: Build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.ULRICH_UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.ULRICH_UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.ULRICH_UNITY_SERIAL }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}

      - name: Create Github Release
        uses: actions/create-release@v1.0.1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: ${{ steps.get_version.outputs.VERSION }}
          body: ${{ steps.get_release_notes.outputs.NOTES }}
          draft: false
          prerelease: false

      - name: Upload Asset to Github release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/urbanairship-${{ steps.get_version.outputs.VERSION }}.unitypackage
          asset_name: urbanairship-${{ steps.get_version.outputs.VERSION }}.unitypackage
          asset_content_type: application/octet-stream

  publish-docs:
    needs: plugin
    uses: ./.github/workflows/publish-docs.yml
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      version: ${{ github.ref_name }}
    secrets: inherit
